from django.urls import path
from . import system_views as system
from . import group_views as groups
from . import article_views as articles
from . import notification_views as notifications
from . import payment_views as payments
from . import attendance_views as attendance
from . import game_points_views as game_points
from . import legacy_test_views as legacy
from . import mock_support_views as support
from .mock_attempt_views import (start_view, answer_view, answers_view, advance_view,
    prepare_view, play_view, speaking_start_view, cheat_view, annotations_view,
    mine_view, detail_view, speaking_upload_view, speaking_audio_view, submit_view)
from .mock_media import group_media_view, group_audio_view, group_image_view
from .mock_import_views import (validate_import_view, commit_import_view, stage_import_media_view,
                               import_by_package_view, import_by_exam_view, resolve_import_issue_view)
from .views import mock_parse_questions_view, mock_import_questions_view

from .views import (desktop_authorize_view, desktop_exchange_view, desktop_version,
                    health, link_child_view, login_view, logout_view, me_view,
                    mock_exam_clone_view, mock_exam_corrected_clone_view,
                    mock_exam_detail_view, mock_exam_preview_view,
                    mock_exam_readiness_view, mock_exam_repair_inspection_view,
                    mock_exam_repair_view, mock_exam_safe_repair_view,
                    mock_exam_sections_view, mock_exams_view,
                    mock_group_content_view, mock_group_questions_view,
                    mock_group_view, mock_question_view, mock_section_groups_view,
                    mock_section_view, my_exam_programs_view, refresh_view, register_view,
                    student_exam_programs_view, user_detail_view, users_view)


urlpatterns = [
    path('game/roster', game_points.roster_view),
    path('game/roster/export', game_points.export_view),
    path('game/status', game_points.status_view),
    path('points/leaderboard', game_points.leaderboard_view),
    path('points/<str:student_id>', game_points.history_view),
    path('points/<str:student_id>/adjust', game_points.adjust_view),
    path('attendance', attendance.list_view),
    path('attendance/stats', attendance.stats_view),
    path('attendance/bulk', attendance.bulk_view),
    path('stats/export/attendance', attendance.export_view),
    path('payments', payments.list_view),
    path('payments/debtors', payments.debtors_view),
    path('payments/bulk', payments.bulk_view),
    path('payments/remind', payments.remind_view),
    path('articles', articles.articles_view),
    path('articles/<str:article_id>', articles.article_view),
    path('notifications', notifications.notifications_view),
    path('notifications/broadcast', notifications.broadcast_view),
    path('notifications/read-all', notifications.read_all_view),
    path('notifications/<str:notification_id>/read', notifications.read_view),
    path('groups', groups.groups_view),
    path('groups/<str:group_id>', groups.group_view),
    path('groups/<str:group_id>/students', groups.add_student_view),
    path('groups/<str:group_id>/students/<str:student_id>', groups.remove_student_view),
    path('settings', system.settings_view),
    path('settings/exam-program-policy', system.program_policy_view),
    path('settings/ielts-bands', system.ielts_bands_view),
    path('audit-logs', system.audit_logs_view),
    path('mock/exams/<str:exam_id>/purchase',support.purchase_view),
    path('mock/exams/<str:exam_id>/confirm-purchase',support.confirm_view),
    path('mock/exams/<str:exam_id>/reject-purchase',support.reject_view),
    path('mock/purchases',support.purchases_view),
    path('mock/attempts',support.attempts_view),
    path('mock/attempts/<str:attempt_id>/force-submit',support.force_view),
    path('mock/attempts/<str:attempt_id>/extend',support.extend_view),
    path('mock/attempts/<str:attempt_id>/reopen',support.reopen_view),
    path('mock/attempts/<str:attempt_id>/certificate',support.certificate_view),
    path('tests',legacy.list_view),
    path('tests/demo/list',legacy.demos_view),
    path('tests/demo/<str:test_id>/submit',legacy.demo_submit_view),
    path('tests/demo/<str:test_id>',legacy.demo_view),
    path('tests/attempts/mine',legacy.mine_view),
    path('tests/attempts',legacy.attempts_view),
    path('tests/attempts/<str:attempt_id>/answer',legacy.answer_view),
    path('tests/attempts/<str:attempt_id>/marks',legacy.marks_view),
    path('tests/attempts/<str:attempt_id>/flag-cheat',legacy.cheat_view),
    path('tests/attempts/<str:attempt_id>/submit',legacy.submit_view),
    path('tests/attempts/<str:attempt_id>/certificate',legacy.certificate_view),
    path('tests/attempts/<str:attempt_id>',legacy.attempt_view),
    path('tests/questions/<str:question_id>/audio',legacy.audio_view),
    path('tests/<str:test_id>/start',legacy.start_view),
    path('tests/<str:test_id>',legacy.test_view),
    path('mock/exams/<str:exam_id>/start', start_view),
    path('mock/attempts/mine', mine_view),
    path('mock/attempts/<str:attempt_id>', detail_view),
    path('mock/attempts/<str:attempt_id>/annotations', annotations_view),
    path('mock/attempts/<str:attempt_id>/speaking/<str:question_id>', speaking_upload_view),
    path('mock/attempts/<str:attempt_id>/answers/<str:question_id>/audio', speaking_audio_view),
    path('mock/attempts/<str:attempt_id>/answer', answer_view),
    path('mock/attempts/<str:attempt_id>/answers', answers_view),
    path('mock/attempts/<str:attempt_id>/submit', submit_view),
    path('mock/attempts/<str:attempt_id>/advance', advance_view),
    path('mock/attempts/<str:attempt_id>/listening/<str:group_id>/prepare', prepare_view),
    path('mock/attempts/<str:attempt_id>/listening/<str:group_id>/play', play_view),
    path('mock/attempts/<str:attempt_id>/speaking/<str:question_id>/start', speaking_start_view),
    path('mock/attempts/<str:attempt_id>/flag-cheat', cheat_view),
    path('mock/groups/<str:group_id>/media', group_media_view),
    path('mock/groups/<str:group_id>/audio', group_audio_view),
    path('mock/groups/<str:group_id>/image', group_image_view),
    path('mock/exam-imports/validate', validate_import_view),
    path('mock/exam-imports/media', stage_import_media_view),
    path('mock/exam-imports', commit_import_view),
    path('mock/exam-imports/by-package/<str:package_id>/revisions/<str:revision>', import_by_package_view),
    path('mock/exam-imports/by-exam/<str:exam_id>', import_by_exam_view),
    path('mock/exam-imports/issues/<str:issue_id>/resolve', resolve_import_issue_view),
    path('mock/parse-questions', mock_parse_questions_view),
    path('mock/groups/<str:group_id>/questions/import', mock_import_questions_view),
    path("health", health), path("desktop-version", desktop_version),
    path("auth/register", register_view), path("auth/login", login_view),
    path("auth/refresh", refresh_view), path("auth/logout", logout_view),
    path("auth/me", me_view), path("auth/link-child", link_child_view),
    path("auth/desktop/authorize", desktop_authorize_view),
    path("auth/desktop/exchange", desktop_exchange_view),
    path("exam-programs/mine", my_exam_programs_view),
    path("exam-programs/students/<str:student_id>", student_exam_programs_view),
    path("mock/exams", mock_exams_view),
    path("mock/exams/<str:exam_id>", mock_exam_detail_view),
    path("mock/exams/<str:exam_id>/clone", mock_exam_clone_view),
    path("mock/exams/<str:exam_id>/readiness", mock_exam_readiness_view),
    path("mock/exams/<str:exam_id>/multilevel-repair-inspection", mock_exam_repair_inspection_view),
    path("mock/exams/<str:exam_id>/apply-multilevel-safe-repair", mock_exam_safe_repair_view),
    path("mock/exams/<str:exam_id>/clone-corrected-multilevel", mock_exam_corrected_clone_view),
    path("mock/exams/<str:exam_id>/repair-multilevel", mock_exam_repair_view),
    path("mock/exams/<str:exam_id>/preview", mock_exam_preview_view),
    path("mock/exams/<str:exam_id>/sections", mock_exam_sections_view),
    path("mock/sections/<str:section_id>", mock_section_view),
    path("mock/sections/<str:section_id>/groups", mock_section_groups_view),
    path("mock/groups/<str:group_id>", mock_group_view),
    path("mock/groups/<str:group_id>/questions", mock_group_questions_view),
    path("mock/groups/<str:group_id>/content", mock_group_content_view),
    path("mock/questions/<str:question_id>", mock_question_view),
    path("users", users_view), path("users/<str:user_id>", user_detail_view),
]
