"""Read-only Django ORM mappings for Prisma-owned BESTWAY tables.

These models are intentionally unmanaged. Field and table names are explicit so a
future migration cannot silently rely on Django's naming conventions.
"""
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Role(models.TextChoices):
    SUPER_ADMIN = "super_admin"; ADMIN = "admin"; TEACHER = "teacher"; STUDENT = "student"; PARENT = "parent"
class AttendanceState(models.TextChoices): PRESENT = "present"; ABSENT = "absent"; LATE = "late"
class PaymentState(models.TextChoices): PAID = "paid"; UNPAID = "unpaid"; PARTIAL = "partial"
class PaymentMethod(models.TextChoices): MANUAL = "manual"
class TestType(models.TextChoices): IELTS = "ielts"; MULTILEVEL = "multilevel"
class ExamProgram(models.TextChoices): IELTS = "IELTS"; MULTILEVEL = "MULTILEVEL"
class PracticeLevel(models.TextChoices): A1 = "A1"; A2 = "A2"; B1 = "B1"; B2 = "B2"; C1 = "C1"
class TestSection(models.TextChoices): LISTENING = "listening"; READING = "reading"; WRITING = "writing"; SPEAKING = "speaking"
class QuestionType(models.TextChoices): MULTIPLE_CHOICE = "multiple_choice"; SHORT_ANSWER = "short_answer"; ESSAY = "essay"; SPEAKING_PROMPT = "speaking_prompt"
class AttemptStatus(models.TextChoices): IN_PROGRESS = "in_progress"; GRADING = "grading"; COMPLETED = "completed"
class NotificationType(models.TextChoices): POINTS = "points"; PAYMENT_REMINDER = "payment_reminder"; TEST_RESULT = "test_result"; ATTENDANCE = "attendance"; ANNOUNCEMENT = "announcement"; GAME = "game"
class PurchaseStatus(models.TextChoices): PENDING = "pending_confirmation"; PURCHASED = "purchased"
class MockExamType(models.TextChoices): IELTS_ACADEMIC = "ielts_academic"; IELTS_GENERAL = "ielts_general"; MULTILEVEL = "multilevel"
class MockSkill(models.TextChoices): LISTENING = "listening"; READING = "reading"; WRITING = "writing"; SPEAKING = "speaking"
class MockQuestionType(models.TextChoices):
    MULTIPLE_CHOICE = "multiple_choice"; MULTI_SELECT = "multi_select"; TRUE_FALSE_NOTGIVEN = "true_false_notgiven"; YES_NO_NOTGIVEN = "yes_no_notgiven"; MATCHING = "matching"; MATCHING_HEADINGS = "matching_headings"; SENTENCE_COMPLETION = "sentence_completion"; NOTE_COMPLETION = "note_completion"; SUMMARY_COMPLETION = "summary_completion"; TABLE_COMPLETION = "table_completion"; SHORT_ANSWER = "short_answer"; MAP_LABELLING = "map_labelling"; ESSAY_TASK1 = "essay_task1"; ESSAY_TASK2 = "essay_task2"; SPEAKING_TASK = "speaking_task"
class MockAttemptStatus(models.TextChoices): IN_PROGRESS = "in_progress"; GRADING = "grading"; COMPLETED = "completed"
class MockAttemptMode(models.TextChoices): PRACTICE = "practice"; TIMED = "timed"
class AssessmentPolicyMode(models.TextChoices): PRACTICE_AUTO_AI = "PRACTICE_AUTO_AI"; FULL_MOCK_AI_WITH_REVIEW = "FULL_MOCK_AI_WITH_REVIEW"; MANUAL_ONLY = "MANUAL_ONLY"
class AssessmentJobStatus(models.TextChoices): PENDING = "PENDING"; PROCESSING = "PROCESSING"; SUCCEEDED = "SUCCEEDED"; RETRY = "RETRY"; FAILED = "FAILED"; NEEDS_REVIEW = "NEEDS_REVIEW"
class AssessmentScoreSource(models.TextChoices): AI = "AI"; TEACHER = "TEACHER"; ADJUDICATED = "ADJUDICATED"
class AssessmentCallStatus(models.TextChoices): STARTED = "STARTED"; SUCCEEDED = "SUCCEEDED"; FAILED = "FAILED"


class LegacyModel(models.Model):
    class Meta: abstract = True; managed = False


class User(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255, db_column="id"); name = models.TextField(db_column="name"); phone = models.TextField(db_column="phone"); email = models.TextField(null=True, db_column="email"); password_hash = models.TextField(db_column="passwordHash"); role = models.CharField(max_length=20, choices=Role.choices, db_column="role"); is_active = models.BooleanField(db_column="isActive"); telegram_chat_id = models.TextField(null=True, db_column="telegramChatId"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "User"
class TelegramLinkToken(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user = models.ForeignKey(User, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); token_hash = models.TextField(db_column="tokenHash"); expires_at = models.DateTimeField(db_column="expiresAt"); used_at = models.DateTimeField(null=True, db_column="usedAt"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "TelegramLinkToken"
class RefreshToken(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user = models.ForeignKey(User, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); token_hash = models.TextField(db_column="tokenHash"); family_id = models.TextField(db_column="familyId"); expires_at = models.DateTimeField(db_column="expiresAt"); revoked_at = models.DateTimeField(null=True, db_column="revokedAt"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "RefreshToken"
class DesktopAuthCode(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user = models.ForeignKey(User, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); code_hash = models.TextField(db_column="codeHash"); code_challenge = models.TextField(db_column="codeChallenge"); device_id = models.TextField(db_column="deviceId"); state = models.TextField(db_column="state"); expires_at = models.DateTimeField(db_column="expiresAt"); used_at = models.DateTimeField(null=True, db_column="usedAt"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "DesktopAuthCode"
class Group(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); name = models.TextField(); teacher = models.ForeignKey(User, null=True, db_column="teacherId", on_delete=models.DO_NOTHING, db_constraint=False); schedule = models.JSONField(null=True); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "Group"
class StudentProfile(LegacyModel):
    user = models.OneToOneField(User, primary_key=True, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); available_programs = ArrayField(models.CharField(max_length=20, choices=ExamProgram.choices), db_column="availablePrograms"); active_program = models.CharField(max_length=20, choices=ExamProgram.choices, null=True, db_column="activeProgram"); is_approved = models.BooleanField(db_column="isApproved"); group = models.ForeignKey(Group, null=True, db_column="groupId", on_delete=models.DO_NOTHING, db_constraint=False); current_points = models.IntegerField(db_column="currentPoints"); link_code = models.TextField(db_column="linkCode"); created_at = models.DateTimeField(db_column="createdAt"); points_period = models.TextField(null=True, db_column="pointsPeriod"); game_qualified = models.BooleanField(db_column="gameQualified"); qualified_at = models.DateTimeField(null=True, db_column="qualifiedAt")
    class Meta(LegacyModel.Meta): db_table = "StudentProfile"
class MonthlyPointsArchive(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); year = models.IntegerField(); month = models.IntegerField(); points = models.IntegerField(); qualified = models.BooleanField(); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MonthlyPointsArchive"; unique_together = (("student", "year", "month"),)
class ParentStudent(LegacyModel):
    # Django has no composite primary key support in 5.2. The first component is
    # a read-only surrogate solely so ORM SELECTs do not request a nonexistent id.
    parent_user_id = models.CharField(primary_key=True, max_length=255, db_column="parentUserId"); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "ParentStudent"; unique_together = (("parent_user_id", "student"),)
class Attendance(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); group = models.ForeignKey(Group, db_column="groupId", on_delete=models.DO_NOTHING, db_constraint=False); date = models.DateField(); state = models.CharField(max_length=10, choices=AttendanceState.choices); marked_by_id = models.TextField(db_column="markedById"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "Attendance"; unique_together = (("student", "group", "date"),)
class Payment(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); month = models.IntegerField(); year = models.IntegerField(); state = models.CharField(max_length=10, choices=PaymentState.choices); amount = models.IntegerField(); method = models.CharField(max_length=10, choices=PaymentMethod.choices); note = models.TextField(null=True); marked_by_id = models.TextField(null=True, db_column="markedById"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "Payment"; unique_together = (("student", "month", "year"),)
class PointsLog(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); change = models.IntegerField(); reason = models.TextField(); by_user_id = models.TextField(null=True, db_column="byUserId"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "PointsLog"
class Test(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); type = models.CharField(max_length=20, choices=TestType.choices); title = models.TextField(); level = models.TextField(null=True); is_demo = models.BooleanField(db_column="isDemo"); is_active = models.BooleanField(db_column="isActive"); duration_minutes = models.IntegerField(null=True, db_column="durationMinutes"); section_question_counts = models.JSONField(null=True, db_column="sectionQuestionCounts"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "Test"
class Question(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); test = models.ForeignKey(Test, db_column="testId", on_delete=models.DO_NOTHING, db_constraint=False); section = models.CharField(max_length=20, choices=TestSection.choices); type = models.CharField(max_length=30, choices=QuestionType.choices); prompt = models.TextField(); options = models.JSONField(null=True); correct_answer = models.TextField(null=True, db_column="correctAnswer"); max_score = models.IntegerField(db_column="maxScore"); audio_url = models.TextField(null=True, db_column="audioUrl"); passage_text = models.TextField(null=True, db_column="passageText"); instructions = models.TextField(null=True); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "Question"
class TestAttempt(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); test = models.ForeignKey(Test, db_column="testId", on_delete=models.DO_NOTHING, db_constraint=False); status = models.CharField(max_length=20, choices=AttemptStatus.choices); question_order = models.JSONField(db_column="questionOrder"); auto_score = models.FloatField(null=True, db_column="autoScore"); manual_score = models.FloatField(null=True, db_column="manualScore"); total_score = models.FloatField(null=True, db_column="totalScore"); anti_cheat_count = models.IntegerField(db_column="antiCheatCount"); started_at = models.DateTimeField(db_column="startedAt"); finished_at = models.DateTimeField(null=True, db_column="finishedAt")
    class Meta(LegacyModel.Meta): db_table = "TestAttempt"
class Answer(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); attempt = models.ForeignKey(TestAttempt, db_column="attemptId", on_delete=models.DO_NOTHING, db_constraint=False); question = models.ForeignKey(Question, db_column="questionId", on_delete=models.DO_NOTHING, db_constraint=False); answer = models.TextField(); score = models.FloatField(null=True); is_graded = models.BooleanField(db_column="isGraded"); graded_by_id = models.TextField(null=True, db_column="gradedById"); comment = models.TextField(null=True); highlights = models.JSONField(null=True); note = models.TextField(null=True); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "Answer"; unique_together = (("attempt", "question"),)
class AntiCheatEvent(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); attempt = models.ForeignKey(TestAttempt, db_column="attemptId", on_delete=models.DO_NOTHING, db_constraint=False); event = models.TextField(); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "AntiCheatEvent"
class VideoLesson(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); title = models.TextField(); description = models.TextField(null=True); price = models.IntegerField(); is_free_for_approved = models.BooleanField(db_column="isFreeForApproved"); file_key = models.TextField(db_column="fileKey"); mime_type = models.TextField(null=True, db_column="mimeType"); thumbnail_key = models.TextField(null=True, db_column="thumbnailKey"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "VideoLesson"
class VideoPurchase(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user = models.ForeignKey(User, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); video = models.ForeignKey(VideoLesson, db_column="videoId", on_delete=models.DO_NOTHING, db_constraint=False); status = models.CharField(max_length=30, choices=PurchaseStatus.choices); method = models.CharField(max_length=10, choices=PaymentMethod.choices); confirmed_by_id = models.TextField(null=True, db_column="confirmedById"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "VideoPurchase"; unique_together = (("user", "video"),)
class Article(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); title = models.TextField(); body = models.TextField(); category = models.TextField(); tags = ArrayField(models.TextField()); author = models.ForeignKey(User, null=True, db_column="authorId", on_delete=models.DO_NOTHING, db_constraint=False); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "Article"
class Teacher(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); name = models.TextField(); specialty = models.TextField(); achievement = models.TextField(null=True); bio = models.TextField(null=True); experience_years = models.IntegerField(null=True, db_column="experienceYears"); photo_key = models.TextField(null=True, db_column="photoKey"); social_url = models.TextField(null=True, db_column="socialUrl"); sort_order = models.IntegerField(db_column="sortOrder"); is_active = models.BooleanField(db_column="isActive"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "Teacher"
class GalleryImage(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); image_key = models.TextField(db_column="imageKey"); label = models.TextField(null=True); link = models.TextField(null=True); alt = models.TextField(null=True); sort_order = models.IntegerField(db_column="sortOrder"); is_active = models.BooleanField(db_column="isActive"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "GalleryImage"
class Notification(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user = models.ForeignKey(User, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); type = models.CharField(max_length=30, choices=NotificationType.choices); text = models.TextField(); read = models.BooleanField(); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "Notification"
class AuditLog(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user_id = models.TextField(null=True, db_column="userId"); action = models.TextField(); entity = models.TextField(); entity_id = models.TextField(null=True, db_column="entityId"); old_value = models.JSONField(null=True, db_column="oldValue"); new_value = models.JSONField(null=True, db_column="newValue"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "AuditLog"
class Setting(LegacyModel):
    key = models.TextField(primary_key=True); value = models.JSONField()
    class Meta(LegacyModel.Meta): db_table = "Setting"
class MockExam(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); assessment_policy = models.CharField(max_length=40, null=True, choices=AssessmentPolicyMode.choices, db_column="assessmentPolicy"); speaking_profile_version = models.TextField(null=True, db_column="speakingProfileVersion"); specification_version = models.TextField(null=True, db_column="specificationVersion"); type = models.CharField(max_length=30, choices=MockExamType.choices); title = models.TextField(); description = models.TextField(null=True); level = models.TextField(null=True); practice_level = models.CharField(max_length=10, null=True, choices=PracticeLevel.choices, db_column="practiceLevel"); is_published = models.BooleanField(db_column="isPublished"); is_demo = models.BooleanField(db_column="isDemo"); price = models.IntegerField(); is_free_for_approved = models.BooleanField(db_column="isFreeForApproved"); created_by_id = models.TextField(null=True, db_column="createdById"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt"); profile = models.TextField(); blueprint_ref = models.TextField(null=True, db_column="blueprintRef"); content_version = models.IntegerField(db_column="contentVersion")
    class Meta(LegacyModel.Meta): db_table = "MockExam"
class MockExamImport(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); created_by_id = models.TextField(db_column="createdById"); package_id = models.TextField(db_column="packageId"); revision = models.IntegerField(); schema_version = models.TextField(db_column="schemaVersion"); profile = models.TextField(); raw_checksum = models.TextField(db_column="rawChecksum"); normalized_checksum = models.TextField(db_column="normalizedChecksum"); validated_checksum = models.TextField(db_column="validatedChecksum"); exam = models.ForeignKey(MockExam, db_column="examId", on_delete=models.DO_NOTHING, db_constraint=False); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MockExamImport"; unique_together = (("created_by_id", "package_id", "revision"),)
class MockImportSourceMap(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); import_record = models.ForeignKey(MockExamImport, db_column="importId", on_delete=models.DO_NOTHING, db_constraint=False); kind = models.TextField(); source_key = models.TextField(db_column="sourceKey"); entity_id = models.TextField(db_column="entityId")
    class Meta(LegacyModel.Meta): db_table = "MockImportSourceMap"; unique_together = (("import_record", "kind", "source_key"),)
class MockImportReviewIssue(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); import_record = models.ForeignKey(MockExamImport, db_column="importId", on_delete=models.DO_NOTHING, db_constraint=False); source_key = models.TextField(null=True, db_column="sourceKey"); entity_kind = models.TextField(null=True, db_column="entityKind"); code = models.TextField(); path = models.TextField(); message = models.TextField(); status = models.TextField(); resolved_by_id = models.TextField(null=True, db_column="resolvedById"); resolved_at = models.DateTimeField(null=True, db_column="resolvedAt"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MockImportReviewIssue"
class MockStagedMedia(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); owner_id = models.TextField(db_column="ownerId"); storage_key = models.TextField(db_column="storageKey"); file_name = models.TextField(db_column="fileName"); mime_type = models.TextField(null=True, db_column="mimeType"); size_bytes = models.IntegerField(db_column="sizeBytes"); checksum = models.TextField(); kind = models.TextField(); expires_at = models.DateTimeField(db_column="expiresAt"); claimed_at = models.DateTimeField(null=True, db_column="claimedAt"); claimed_import_id = models.TextField(null=True, db_column="claimedImportId"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MockStagedMedia"
class MockPurchase(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); user = models.ForeignKey(User, db_column="userId", on_delete=models.DO_NOTHING, db_constraint=False); exam = models.ForeignKey(MockExam, db_column="examId", on_delete=models.DO_NOTHING, db_constraint=False); status = models.CharField(max_length=30, choices=PurchaseStatus.choices); method = models.CharField(max_length=10, choices=PaymentMethod.choices); amount = models.IntegerField(); confirmed_by_id = models.TextField(null=True, db_column="confirmedById"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "MockPurchase"; unique_together = (("user", "exam"),)
class MockSection(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); exam = models.ForeignKey(MockExam, db_column="examId", on_delete=models.DO_NOTHING, db_constraint=False); skill = models.CharField(max_length=20, choices=MockSkill.choices); title = models.TextField(null=True); sort_order = models.IntegerField(db_column="sortOrder"); duration_minutes = models.IntegerField(null=True, db_column="durationMinutes"); instructions = models.TextField(null=True)
    class Meta(LegacyModel.Meta): db_table = "MockSection"; unique_together = (("exam", "skill"),)
class MockQuestionGroup(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); section = models.ForeignKey(MockSection, db_column="sectionId", on_delete=models.DO_NOTHING, db_constraint=False); sort_order = models.IntegerField(db_column="sortOrder"); title = models.TextField(null=True); instructions = models.TextField(null=True); passage_text = models.TextField(null=True, db_column="passageText"); content_html = models.TextField(null=True, db_column="contentHtml"); audio_script = models.TextField(null=True, db_column="audioScript"); content_layout = models.TextField(null=True, db_column="contentLayout"); options_reusable = models.BooleanField(null=True, db_column="optionsReusable"); audio_key = models.TextField(null=True, db_column="audioKey"); image_key = models.TextField(null=True, db_column="imageKey"); max_score = models.IntegerField(null=True, db_column="maxScore"); stimulus_ref = models.TextField(null=True, db_column="stimulusRef"); part_number = models.IntegerField(null=True, db_column="partNumber"); audio_play_limit = models.IntegerField(db_column="audioPlayLimit"); audio_duration_sec = models.IntegerField(null=True, db_column="audioDurationSec"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MockQuestionGroup"
class MockQuestion(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); group = models.ForeignKey(MockQuestionGroup, db_column="groupId", on_delete=models.DO_NOTHING, db_constraint=False); number = models.IntegerField(); sort_order = models.IntegerField(db_column="sortOrder"); type = models.CharField(max_length=40, choices=MockQuestionType.choices); prompt = models.TextField(); options = models.JSONField(null=True); correct_answers = models.JSONField(null=True, db_column="correctAnswers"); points = models.IntegerField(); word_limit = models.IntegerField(null=True, db_column="wordLimit"); answer_rule = models.TextField(null=True, db_column="answerRule"); accepted_variants = models.JSONField(null=True, db_column="acceptedVariants"); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MockQuestion"
class MockAttempt(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); speaking_profile_version = models.TextField(null=True, db_column="speakingProfileVersion"); specification_version = models.TextField(null=True, db_column="specificationVersion"); score_method = models.TextField(null=True, db_column="scoreMethod"); score_version = models.TextField(null=True, db_column="scoreVersion"); standard_scores = models.JSONField(null=True, db_column="standardScores"); overall_score = models.FloatField(null=True, db_column="overallScore"); media_state = models.JSONField(null=True, db_column="mediaState"); exam = models.ForeignKey(MockExam, db_column="examId", on_delete=models.DO_NOTHING, db_constraint=False); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); status = models.CharField(max_length=20, choices=MockAttemptStatus.choices); started_at = models.DateTimeField(db_column="startedAt"); submitted_at = models.DateTimeField(null=True, db_column="submittedAt"); finished_at = models.DateTimeField(null=True, db_column="finishedAt"); raw_scores = models.JSONField(null=True, db_column="rawScores"); section_bands = models.JSONField(null=True, db_column="sectionBands"); overall_band = models.FloatField(null=True, db_column="overallBand"); cefr_level = models.TextField(null=True, db_column="cefrLevel"); anti_cheat_count = models.IntegerField(db_column="antiCheatCount"); mode = models.CharField(max_length=20, choices=MockAttemptMode.choices); deadline_at = models.DateTimeField(null=True, db_column="deadlineAt"); annotations = models.JSONField(null=True); flow_mode = models.TextField(null=True, db_column="flowMode"); current_skill = models.CharField(max_length=20, null=True, choices=MockSkill.choices, db_column="currentSkill"); section_deadlines = models.JSONField(null=True, db_column="sectionDeadlines"); overall_deadline_at = models.DateTimeField(null=True, db_column="overallDeadlineAt"); audio_plays = models.JSONField(null=True, db_column="audioPlays"); submitted_sections = models.JSONField(null=True, db_column="submittedSections")
    class Meta(LegacyModel.Meta): db_table = "MockAttempt"
class MockAnswer(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); attempt = models.ForeignKey(MockAttempt, db_column="attemptId", on_delete=models.DO_NOTHING, db_constraint=False); question = models.ForeignKey(MockQuestion, db_column="questionId", on_delete=models.DO_NOTHING, db_constraint=False); response = models.TextField(); audio_key = models.TextField(null=True, db_column="audioKey"); is_correct = models.BooleanField(null=True, db_column="isCorrect"); score = models.FloatField(null=True); is_graded = models.BooleanField(db_column="isGraded"); graded_by_id = models.TextField(null=True, db_column="gradedById"); feedback = models.TextField(null=True); rubric_scores = models.JSONField(null=True, db_column="rubricScores"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "MockAnswer"; unique_together = (("attempt", "question"),)
class MockCheatEvent(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); attempt = models.ForeignKey(MockAttempt, db_column="attemptId", on_delete=models.DO_NOTHING, db_constraint=False); event = models.TextField(); created_at = models.DateTimeField(db_column="createdAt")
    class Meta(LegacyModel.Meta): db_table = "MockCheatEvent"
class AssessmentJob(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); attempt = models.ForeignKey(MockAttempt, db_column="attemptId", on_delete=models.DO_NOTHING, db_constraint=False); student = models.ForeignKey(StudentProfile, db_column="studentId", on_delete=models.DO_NOTHING, db_constraint=False); program = models.TextField(); skill = models.CharField(max_length=20, choices=MockSkill.choices); input_hash = models.TextField(db_column="inputHash"); input_snapshot = models.JSONField(db_column="inputSnapshot"); generation = models.IntegerField(); rubric_version = models.TextField(db_column="rubricVersion"); prompt_version = models.TextField(db_column="promptVersion"); policy_mode = models.CharField(max_length=40, choices=AssessmentPolicyMode.choices, db_column="policyMode"); status = models.CharField(max_length=20, choices=AssessmentJobStatus.choices); version = models.IntegerField(); attempt_count = models.IntegerField(db_column="attemptCount"); lease_token = models.TextField(null=True, db_column="leaseToken"); lease_expires_at = models.DateTimeField(null=True, db_column="leaseExpiresAt"); retry_at = models.DateTimeField(null=True, db_column="retryAt"); started_at = models.DateTimeField(null=True, db_column="startedAt"); completed_at = models.DateTimeField(null=True, db_column="completedAt"); failure_code = models.TextField(null=True, db_column="failureCode"); selected_evaluation_id = models.TextField(null=True, db_column="selectedEvaluationId"); ai_score = models.FloatField(null=True, db_column="aiScore"); teacher_score = models.FloatField(null=True, db_column="teacherScore"); final_score = models.FloatField(null=True, db_column="finalScore"); final_score_source = models.CharField(max_length=20, null=True, choices=AssessmentScoreSource.choices, db_column="finalScoreSource"); confidence = models.FloatField(null=True); final_result = models.JSONField(null=True, db_column="finalResult"); approved_feedback = models.JSONField(null=True, db_column="approvedFeedback"); created_at = models.DateTimeField(db_column="createdAt"); updated_at = models.DateTimeField(db_column="updatedAt")
    class Meta(LegacyModel.Meta): db_table = "AssessmentJob"; unique_together = (("attempt", "skill", "input_hash", "generation"),)
class AssessmentEvaluation(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); job = models.ForeignKey(AssessmentJob, db_column="jobId", on_delete=models.DO_NOTHING, db_constraint=False); role = models.TextField(); attempt_number = models.IntegerField(db_column="attemptNumber"); input_hash = models.TextField(db_column="inputHash"); status = models.CharField(max_length=20, choices=AssessmentCallStatus.choices); provider = models.TextField(); model = models.TextField(); result = models.JSONField(null=True); confidence = models.FloatField(null=True); input_tokens = models.IntegerField(null=True, db_column="inputTokens"); output_tokens = models.IntegerField(null=True, db_column="outputTokens"); latency_ms = models.IntegerField(null=True, db_column="latencyMs"); failure_code = models.TextField(null=True, db_column="failureCode"); uncertain = models.BooleanField(); started_at = models.DateTimeField(db_column="startedAt"); completed_at = models.DateTimeField(null=True, db_column="completedAt")
    class Meta(LegacyModel.Meta): db_table = "AssessmentEvaluation"; unique_together = (("job", "role", "attempt_number"),)
class SpeechTranscript(LegacyModel):
    id = models.CharField(primary_key=True, max_length=255); job = models.ForeignKey(AssessmentJob, db_column="jobId", on_delete=models.DO_NOTHING, db_constraint=False); question_id = models.TextField(db_column="questionId"); audio_hash = models.TextField(db_column="audioHash"); status = models.CharField(max_length=20, choices=AssessmentCallStatus.choices); attempt_number = models.IntegerField(db_column="attemptNumber"); text = models.TextField(null=True); segments = models.JSONField(null=True); confidence = models.FloatField(null=True); provider = models.TextField(); model = models.TextField(); duration_ms = models.IntegerField(null=True, db_column="durationMs"); pronunciation_evidence = models.TextField(db_column="pronunciationEvidence"); failure_code = models.TextField(null=True, db_column="failureCode"); uncertain = models.BooleanField(); started_at = models.DateTimeField(db_column="startedAt"); completed_at = models.DateTimeField(null=True, db_column="completedAt")
    class Meta(LegacyModel.Meta): db_table = "SpeechTranscript"; unique_together = (("job", "question_id", "attempt_number"),)
